package com.amsidh.mvc.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.events.Event;
import com.itextpdf.kernel.events.IEventHandler;
import com.itextpdf.kernel.events.PdfDocumentEvent;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.Rectangle;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfPage;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.PdfCanvas;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
public class DynamicTablePdfService {

    private final ObjectMapper objectMapper;
    private static final float MARGIN = 20;
    private static final float FONT_SIZE = 10;
    private static final float CELL_PADDING = 5;
    private static final float BORDER_WIDTH = 1f;
    private static final String HEADER_TEXT = "Dynamic Table Report";
    private static final String FOOTER_TEXT = "Generated by DynamicTablePdfService";

    public DynamicTablePdfService() {
        this.objectMapper = new ObjectMapper();
    }

    public byte[] generateDynamicTablePdf(String jsonString) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(baos);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);
        document.setMargins(MARGIN + 30, MARGIN, MARGIN + 30, MARGIN); // extra margin for header/footer

        PdfFont font = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        PdfFont boldFont = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);

        // Add event handler for header/footer
        pdf.addEventHandler(PdfDocumentEvent.END_PAGE, new HeaderFooterEventHandler(document, font, boldFont));


        // Parse JSON
        LinkedHashMap<String, Object> jsonMap = objectMapper.readValue(
                jsonString, new TypeReference<>() {
                });

        // Create main table with 2 columns
        Table mainTable = new Table(UnitValue.createPercentArray(new float[]{1, 2}))
                .useAllAvailableWidth();
        mainTable.setBorder(new SolidBorder(ColorConstants.BLACK, BORDER_WIDTH));

        // Process JSON content
        processJsonToTable(mainTable, jsonMap, boldFont, font, 0);

        document.add(mainTable);
        document.close();
        return baos.toByteArray();
    }

    private void processJsonToTable(Table parentTable, Map<String, Object> data,
                                    PdfFont boldFont, PdfFont normalFont,
                                    int level) {
        data.forEach((key, value) -> {
            Cell keyCell = new Cell()
                    .add(new Paragraph(key)
                            .setFont(boldFont)
                            .setFontSize(FONT_SIZE))
                    .setPadding(CELL_PADDING)
                    .setBorder(new SolidBorder(ColorConstants.BLACK, BORDER_WIDTH));

            Cell valueCell = new Cell()
                    .setPadding(CELL_PADDING)
                    .setBorder(new SolidBorder(ColorConstants.BLACK, BORDER_WIDTH));

            if (value instanceof Map) {
                Table nestedTable = new Table(UnitValue.createPercentArray(new float[]{1, 2}))
                        .useAllAvailableWidth();
                nestedTable.setBorder(new SolidBorder(ColorConstants.GRAY, BORDER_WIDTH));
                processJsonToTable(nestedTable, (Map<String, Object>) value, boldFont, normalFont, level + 1);
                valueCell.add(nestedTable);
            } else if (value instanceof List) {
                List<?> list = (List<?>) value;
                for (Object item : list) {
                    if (item instanceof Map) {
                        Table nestedTable = new Table(UnitValue.createPercentArray(new float[]{1, 2}))
                                .useAllAvailableWidth();
                        nestedTable.setBorder(new SolidBorder(ColorConstants.GRAY, BORDER_WIDTH));
                        processJsonToTable(nestedTable, (Map<String, Object>) item, boldFont, normalFont, level + 1);
                        valueCell.add(nestedTable);
                    } else {
                        valueCell.add(new Paragraph(String.valueOf(item))
                                .setFont(normalFont)
                                .setFontSize(FONT_SIZE));
                    }
                }
            } else {
                valueCell.add(new Paragraph(String.valueOf(value))
                        .setFont(normalFont)
                        .setFontSize(FONT_SIZE));
            }

            parentTable.addCell(keyCell);
            parentTable.addCell(valueCell);
        });
    }

    // ====== ADD THIS inner class ======
    private static class HeaderFooterEventHandler implements IEventHandler {
        private final Document document;
        private final PdfFont normalFont;
        private final PdfFont boldFont;

        public HeaderFooterEventHandler(Document document, PdfFont normalFont, PdfFont boldFont) {
            this.document = document;
            this.normalFont = normalFont;
            this.boldFont = boldFont;
        }

        @Override
        public void handleEvent(Event event) {
            PdfDocumentEvent docEvent = (PdfDocumentEvent) event;
            PdfPage page = docEvent.getPage();
            PdfCanvas canvas = new PdfCanvas(page.newContentStreamBefore(), page.getResources(), docEvent.getDocument());

            Rectangle pageSize = page.getPageSize();

            float x = pageSize.getWidth() / 2;
            float headerY = pageSize.getTop() - 20;
            float footerY = pageSize.getBottom() + 20;

            int pageNumber = docEvent.getDocument().getPageNumber(page);
            int totalPageCount = docEvent.getDocument().getNumberOfPages();

            // Header - Bold font
            canvas.beginText()
                    .setFontAndSize(boldFont, 12)  // <-- using boldFont
                    .moveText(x - (boldFont.getWidth(HEADER_TEXT, 12) / 2), headerY)
                    .showText(HEADER_TEXT)
                    .endText();

            // Footer with correct page numbering
            String footer = FOOTER_TEXT + " | " + getFormattedTimestamp() + " | Page " + pageNumber;
            float textWidth = normalFont.getWidth(footer, 9);

            canvas.beginText()
                    .setFontAndSize(normalFont, 9)
                    .moveText(x - textWidth / 2, footerY)
                    .showText(footer)
                    .endText();

            canvas.release();
        }

        private String getFormattedTimestamp() {
            ZonedDateTime now = ZonedDateTime.now(ZoneId.of("Asia/Kolkata"));
            return now.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS z"));
        }
    }
}
